# Generated by Django 5.0.7 on 2024-10-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='answer',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
