# Generated by Django 5.0.7 on 2024-11-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_postcomment_answer_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
