# Generated by Django 5.0.7 on 2024-11-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='metauser',
            name='image',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
